version: '3'
services:
  async-sanic-poc:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENV: 'development'
    volumes:
      - ./service:/opt/service